/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>MicroPython.jflex</tt>
 */
class MicroPythonLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\6\1\7\1\7\1\7\22\0\1\1\1\13\1\0"+
    "\1\5\4\0\1\20\1\21\1\16\1\14\1\24\1\15\1\25\1\17"+
    "\12\4\1\23\1\22\1\10\1\12\1\11\2\0\2\2\1\44\10\2"+
    "\1\42\1\32\2\2\1\35\12\2\4\0\1\3\1\0\1\46\1\2"+
    "\1\34\1\50\1\51\1\26\1\2\1\40\1\33\2\2\1\45\1\31"+
    "\1\41\1\30\1\47\1\2\1\27\1\43\1\37\1\52\1\2\1\53"+
    "\1\2\1\36\1\2\12\0\1\7\44\0\1\2\12\0\1\2\4\0"+
    "\1\2\5\0\27\2\1\0\37\2\1\0\u01ca\2\4\0\14\2\16\0"+
    "\5\2\7\0\1\2\1\0\1\2\201\0\5\2\1\0\2\2\2\0"+
    "\4\2\1\0\1\2\6\0\1\2\1\0\3\2\1\0\1\2\1\0"+
    "\24\2\1\0\123\2\1\0\213\2\10\0\246\2\1\0\46\2\2\0"+
    "\1\2\7\0\47\2\110\0\33\2\5\0\3\2\55\0\53\2\25\0"+
    "\12\4\4\0\2\2\1\0\143\2\1\0\1\2\17\0\2\2\7\0"+
    "\2\2\12\4\3\2\2\0\1\2\20\0\1\2\1\0\36\2\35\0"+
    "\131\2\13\0\1\2\16\0\12\4\41\2\11\0\2\2\4\0\1\2"+
    "\5\0\26\2\4\0\1\2\11\0\1\2\3\0\1\2\27\0\31\2"+
    "\107\0\25\2\1\0\10\2\106\0\66\2\3\0\1\2\22\0\1\2"+
    "\7\0\12\2\4\0\12\4\1\0\20\2\4\0\10\2\2\0\2\2"+
    "\2\0\26\2\1\0\7\2\1\0\1\2\3\0\4\2\3\0\1\2"+
    "\20\0\1\2\15\0\2\2\1\0\3\2\4\0\12\4\2\2\23\0"+
    "\6\2\4\0\2\2\2\0\26\2\1\0\7\2\1\0\2\2\1\0"+
    "\2\2\1\0\2\2\37\0\4\2\1\0\1\2\7\0\12\4\2\0"+
    "\3\2\20\0\11\2\1\0\3\2\1\0\26\2\1\0\7\2\1\0"+
    "\2\2\1\0\5\2\3\0\1\2\22\0\1\2\17\0\2\2\4\0"+
    "\12\4\11\0\1\2\13\0\10\2\2\0\2\2\2\0\26\2\1\0"+
    "\7\2\1\0\2\2\1\0\5\2\3\0\1\2\36\0\2\2\1\0"+
    "\3\2\4\0\12\4\1\0\1\2\21\0\1\2\1\0\6\2\3\0"+
    "\3\2\1\0\4\2\3\0\2\2\1\0\1\2\1\0\2\2\3\0"+
    "\2\2\3\0\3\2\3\0\14\2\26\0\1\2\25\0\12\4\25\0"+
    "\10\2\1\0\3\2\1\0\27\2\1\0\20\2\3\0\1\2\32\0"+
    "\3\2\5\0\2\2\4\0\12\4\20\0\1\2\4\0\10\2\1\0"+
    "\3\2\1\0\27\2\1\0\12\2\1\0\5\2\3\0\1\2\40\0"+
    "\1\2\1\0\2\2\4\0\12\4\1\0\2\2\22\0\10\2\1\0"+
    "\3\2\1\0\51\2\2\0\1\2\20\0\1\2\5\0\3\2\10\0"+
    "\3\2\4\0\12\4\12\0\6\2\5\0\22\2\3\0\30\2\1\0"+
    "\11\2\1\0\1\2\2\0\7\2\37\0\12\4\21\0\60\2\1\0"+
    "\2\2\14\0\7\2\11\0\12\4\47\0\2\2\1\0\1\2\2\0"+
    "\2\2\1\0\1\2\2\0\1\2\6\0\4\2\1\0\7\2\1\0"+
    "\3\2\1\0\1\2\1\0\1\2\2\0\2\2\1\0\4\2\1\0"+
    "\2\2\11\0\1\2\2\0\5\2\1\0\1\2\11\0\12\4\2\0"+
    "\4\2\40\0\1\2\37\0\12\4\26\0\10\2\1\0\44\2\33\0"+
    "\5\2\163\0\53\2\24\0\1\2\12\4\6\0\6\2\4\0\4\2"+
    "\3\0\1\2\3\0\2\2\7\0\3\2\4\0\15\2\14\0\1\2"+
    "\1\0\12\4\6\0\46\2\1\0\1\2\5\0\1\2\2\0\53\2"+
    "\1\0\u014d\2\1\0\4\2\2\0\7\2\1\0\1\2\1\0\4\2"+
    "\2\0\51\2\1\0\4\2\2\0\41\2\1\0\4\2\2\0\7\2"+
    "\1\0\1\2\1\0\4\2\2\0\17\2\1\0\71\2\1\0\4\2"+
    "\2\0\103\2\45\0\20\2\20\0\126\2\2\0\6\2\3\0\u026c\2"+
    "\2\0\21\2\1\0\32\2\5\0\113\2\6\0\10\2\7\0\15\2"+
    "\1\0\4\2\16\0\22\2\16\0\22\2\16\0\15\2\1\0\3\2"+
    "\17\0\64\2\43\0\1\2\4\0\1\2\3\0\12\4\46\0\12\4"+
    "\6\0\130\2\10\0\5\2\2\0\42\2\1\0\1\2\5\0\106\2"+
    "\12\0\37\2\47\0\12\4\36\2\2\0\5\2\13\0\54\2\4\0"+
    "\32\2\6\0\12\4\46\0\27\2\11\0\65\2\53\0\12\4\6\0"+
    "\12\4\15\0\1\2\135\0\57\2\21\0\7\2\4\0\12\4\51\0"+
    "\36\2\15\0\2\2\12\4\54\2\32\0\44\2\34\0\12\4\3\0"+
    "\3\2\12\4\44\2\2\0\11\2\140\0\4\2\1\0\4\2\3\0"+
    "\2\2\11\0\300\2\100\0\u0116\2\2\0\6\2\2\0\46\2\2\0"+
    "\6\2\2\0\10\2\1\0\1\2\1\0\1\2\1\0\1\2\1\0"+
    "\37\2\2\0\65\2\1\0\7\2\1\0\1\2\3\0\3\2\1\0"+
    "\7\2\3\0\4\2\2\0\6\2\4\0\15\2\5\0\3\2\1\0"+
    "\7\2\53\0\1\7\1\7\107\0\1\2\15\0\1\2\20\0\15\2"+
    "\145\0\1\2\4\0\1\2\2\0\12\2\1\0\1\2\3\0\5\2"+
    "\6\0\1\2\1\0\1\2\1\0\1\2\1\0\4\2\1\0\13\2"+
    "\2\0\4\2\5\0\5\2\4\0\1\2\64\0\2\2\u0a7b\0\57\2"+
    "\1\0\57\2\1\0\205\2\6\0\4\2\3\0\2\2\14\0\46\2"+
    "\1\0\1\2\5\0\1\2\2\0\70\2\7\0\1\2\20\0\27\2"+
    "\11\0\7\2\1\0\7\2\1\0\7\2\1\0\7\2\1\0\7\2"+
    "\1\0\7\2\1\0\7\2\1\0\7\2\120\0\1\2\u01d5\0\2\2"+
    "\52\0\5\2\5\0\2\2\4\0\126\2\6\0\3\2\1\0\132\2"+
    "\1\0\4\2\5\0\51\2\3\0\136\2\21\0\33\2\65\0\20\2"+
    "\u0200\0\u19b6\2\112\0\u51d6\2\52\0\u048d\2\103\0\56\2\2\0\u010d\2"+
    "\3\0\20\2\12\4\2\2\24\0\57\2\20\0\37\2\2\0\106\2"+
    "\61\0\11\2\2\0\147\2\2\0\44\2\1\0\10\2\77\0\13\2"+
    "\1\0\3\2\1\0\4\2\1\0\27\2\35\0\64\2\16\0\62\2"+
    "\34\0\12\4\30\0\6\2\3\0\1\2\1\0\1\2\2\0\12\4"+
    "\34\2\12\0\27\2\31\0\35\2\7\0\57\2\34\0\1\2\12\4"+
    "\6\0\5\2\1\0\12\2\12\4\5\2\1\0\51\2\27\0\3\2"+
    "\1\0\10\2\4\0\12\4\6\0\27\2\3\0\1\2\3\0\62\2"+
    "\1\0\1\2\3\0\2\2\2\0\5\2\2\0\1\2\1\0\1\2"+
    "\30\0\3\2\2\0\13\2\7\0\3\2\14\0\6\2\2\0\6\2"+
    "\2\0\6\2\11\0\7\2\1\0\7\2\1\0\53\2\1\0\12\2"+
    "\12\0\163\2\15\0\12\4\6\0\u2ba4\2\14\0\27\2\4\0\61\2"+
    "\u2104\0\u016e\2\2\0\152\2\46\0\7\2\14\0\5\2\5\0\1\2"+
    "\1\0\12\2\1\0\15\2\1\0\5\2\1\0\1\2\1\0\2\2"+
    "\1\0\2\2\1\0\154\2\41\0\u016b\2\22\0\100\2\2\0\66\2"+
    "\50\0\14\2\164\0\5\2\1\0\207\2\23\0\12\4\7\0\32\2"+
    "\6\0\32\2\13\0\131\2\3\0\6\2\2\0\6\2\2\0\6\2"+
    "\2\0\3\2\43\0\14\2\1\0\32\2\1\0\23\2\1\0\2\2"+
    "\1\0\17\2\2\0\16\2\42\0\173\2\u0185\0\35\2\3\0\61\2"+
    "\57\0\40\2\20\0\21\2\1\0\10\2\6\0\46\2\12\0\36\2"+
    "\2\0\44\2\4\0\10\2\60\0\236\2\2\0\12\4\6\0\44\2"+
    "\4\0\44\2\4\0\50\2\10\0\64\2\234\0\u0137\2\11\0\26\2"+
    "\12\0\10\2\230\0\6\2\2\0\1\2\1\0\54\2\1\0\2\2"+
    "\3\0\1\2\2\0\27\2\12\0\27\2\11\0\37\2\101\0\23\2"+
    "\1\0\2\2\12\0\26\2\12\0\32\2\106\0\70\2\6\0\2\2"+
    "\100\0\1\2\17\0\4\2\1\0\3\2\1\0\33\2\54\0\35\2"+
    "\3\0\35\2\43\0\10\2\1\0\34\2\33\0\66\2\12\0\26\2"+
    "\12\0\23\2\15\0\22\2\156\0\111\2\67\0\63\2\15\0\63\2"+
    "\u0310\0\65\2\56\0\12\4\23\0\55\2\40\0\31\2\7\0\12\4"+
    "\11\0\44\2\17\0\12\4\20\0\43\2\3\0\1\2\14\0\60\2"+
    "\16\0\4\2\13\0\12\4\1\2\1\0\1\2\43\0\22\2\1\0"+
    "\31\2\124\0\7\2\1\0\1\2\1\0\4\2\1\0\17\2\1\0"+
    "\12\2\7\0\57\2\21\0\12\4\13\0\10\2\2\0\2\2\2\0"+
    "\26\2\1\0\7\2\1\0\2\2\1\0\5\2\3\0\1\2\22\0"+
    "\1\2\14\0\5\2\236\0\65\2\22\0\4\2\5\0\12\4\46\0"+
    "\60\2\24\0\2\2\1\0\1\2\10\0\12\4\246\0\57\2\51\0"+
    "\4\2\44\0\60\2\24\0\1\2\13\0\12\4\46\0\53\2\25\0"+
    "\12\4\66\0\32\2\26\0\12\4\u0166\0\100\2\12\4\25\0\1\2"+
    "\u01c0\0\71\2\u0107\0\11\2\1\0\45\2\21\0\1\2\17\0\12\4"+
    "\30\0\36\2\u0370\0\u039a\2\346\0\304\2\u0abc\0\u042f\2\u0fd1\0\u0247\2"+
    "\u21b9\0\u0239\2\7\0\37\2\1\0\12\4\146\0\36\2\22\0\60\2"+
    "\20\0\4\2\14\0\12\4\11\0\25\2\5\0\23\2\u0370\0\105\2"+
    "\13\0\1\2\102\0\15\2\100\0\1\2\37\0\u17ed\2\23\0\u02f3\2"+
    "\u250d\0\2\2\u0bfe\0\153\2\5\0\15\2\3\0\11\2\7\0\12\2"+
    "\u1766\0\125\2\1\0\107\2\1\0\2\2\2\0\1\2\2\0\2\2"+
    "\2\0\4\2\1\0\14\2\1\0\1\2\1\0\7\2\1\0\101\2"+
    "\1\0\4\2\2\0\10\2\1\0\7\2\1\0\34\2\1\0\4\2"+
    "\1\0\5\2\1\0\1\2\3\0\7\2\1\0\u0154\2\2\0\31\2"+
    "\1\0\31\2\1\0\37\2\1\0\31\2\1\0\37\2\1\0\31\2"+
    "\1\0\37\2\1\0\31\2\1\0\37\2\1\0\31\2\1\0\10\2"+
    "\2\0\62\4\u1000\0\305\2\73\0\104\2\14\0\12\4\u04a6\0\4\2"+
    "\1\0\33\2\1\0\2\2\1\0\1\2\2\0\1\2\1\0\12\2"+
    "\1\0\4\2\1\0\1\2\1\0\1\2\6\0\1\2\4\0\1\2"+
    "\1\0\1\2\1\0\1\2\1\0\3\2\1\0\2\2\1\0\1\2"+
    "\2\0\1\2\1\0\1\2\1\0\1\2\1\0\1\2\1\0\1\2"+
    "\1\0\2\2\1\0\1\2\2\0\4\2\1\0\7\2\1\0\4\2"+
    "\1\0\4\2\1\0\1\2\1\0\12\2\1\0\21\2\5\0\3\2"+
    "\1\0\5\2\1\0\21\2\u1144\0\ua6d7\2\51\0\u1035\2\13\0\336\2"+
    "\2\0\u1682\2\u295e\0\u021e\2\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\1\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\16\3\2\0\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\2\3\1\27\1\3\1\30"+
    "\20\3\1\31\4\3\1\32\1\3\1\33\1\3\1\34"+
    "\2\3\1\35\4\3\1\36\1\37\1\40\1\41\1\3"+
    "\1\42\4\3\1\43\1\44\1\45\1\46\1\3\1\47"+
    "\10\3\1\50\4\3\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\130\0\204\0\260\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\54\0\u018c\0\54\0\u01b8\0\54\0\54"+
    "\0\54\0\54\0\54\0\54\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\260\0\54\0\54\0\54\0\54"+
    "\0\54\0\54\0\u0478\0\u04a4\0\130\0\u04d0\0\130\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\130"+
    "\0\u07bc\0\u07e8\0\u0814\0\u0840\0\130\0\u086c\0\130\0\u0898"+
    "\0\130\0\u08c4\0\u08f0\0\130\0\u091c\0\u0948\0\u0974\0\u09a0"+
    "\0\130\0\130\0\130\0\130\0\u09cc\0\130\0\u09f8\0\u0a24"+
    "\0\u0a50\0\u0a7c\0\130\0\130\0\130\0\130\0\u0aa8\0\130"+
    "\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08"+
    "\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\3\1\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\4\1\30\1\31\1\32\2\4\1\33\1\34"+
    "\1\35\4\4\1\36\1\37\1\40\1\41\1\4\1\42"+
    "\56\0\1\4\1\43\1\4\21\0\26\4\4\0\1\5"+
    "\47\0\6\44\1\3\1\0\44\44\12\0\1\45\53\0"+
    "\1\46\53\0\1\47\53\0\1\50\52\0\1\51\61\0"+
    "\1\52\36\0\1\4\1\43\1\4\21\0\1\4\1\53"+
    "\24\4\2\0\1\4\1\43\1\4\21\0\23\4\1\54"+
    "\2\4\2\0\1\4\1\43\1\4\21\0\1\4\1\55"+
    "\24\4\2\0\1\4\1\43\1\4\21\0\5\4\1\56"+
    "\20\4\2\0\1\4\1\43\1\4\21\0\1\57\2\4"+
    "\1\60\7\4\1\61\12\4\2\0\1\4\1\43\1\4"+
    "\21\0\2\4\1\62\23\4\2\0\1\4\1\43\1\4"+
    "\21\0\20\4\1\63\5\4\2\0\1\4\1\43\1\4"+
    "\21\0\23\4\1\64\2\4\2\0\1\4\1\43\1\4"+
    "\21\0\2\4\1\65\21\4\1\66\1\4\2\0\1\4"+
    "\1\43\1\4\21\0\13\4\1\67\12\4\2\0\1\4"+
    "\1\43\1\4\21\0\1\4\1\70\24\4\2\0\1\4"+
    "\1\43\1\4\21\0\23\4\1\71\2\4\2\0\1\4"+
    "\1\43\1\4\21\0\17\4\1\72\6\4\2\0\1\4"+
    "\1\43\1\4\21\0\12\4\1\73\13\4\2\0\1\4"+
    "\1\0\1\4\21\0\26\4\2\0\1\4\1\43\1\4"+
    "\21\0\2\4\1\74\23\4\2\0\1\4\1\43\1\4"+
    "\21\0\11\4\1\75\14\4\2\0\1\4\1\43\1\4"+
    "\21\0\6\4\1\76\17\4\2\0\1\4\1\43\1\4"+
    "\21\0\21\4\1\77\4\4\2\0\1\4\1\43\1\4"+
    "\21\0\11\4\1\100\7\4\1\101\4\4\2\0\1\4"+
    "\1\43\1\4\21\0\13\4\1\102\12\4\2\0\1\4"+
    "\1\43\1\4\21\0\5\4\1\103\20\4\2\0\1\4"+
    "\1\43\1\4\21\0\20\4\1\104\5\4\2\0\1\4"+
    "\1\43\1\4\21\0\11\4\1\105\14\4\2\0\1\4"+
    "\1\43\1\4\21\0\17\4\1\106\6\4\2\0\1\4"+
    "\1\43\1\4\21\0\22\4\1\107\3\4\2\0\1\4"+
    "\1\43\1\4\21\0\5\4\1\110\20\4\2\0\1\4"+
    "\1\43\1\4\21\0\1\111\25\4\2\0\1\4\1\43"+
    "\1\4\21\0\15\4\1\112\10\4\2\0\1\4\1\43"+
    "\1\4\21\0\5\4\1\113\20\4\2\0\1\4\1\43"+
    "\1\4\21\0\3\4\1\114\22\4\2\0\1\4\1\43"+
    "\1\4\21\0\24\4\1\115\1\4\2\0\1\4\1\43"+
    "\1\4\21\0\1\4\1\116\24\4\2\0\1\4\1\43"+
    "\1\4\21\0\2\4\1\117\23\4\2\0\1\4\1\43"+
    "\1\4\21\0\24\4\1\120\1\4\2\0\1\4\1\43"+
    "\1\4\21\0\15\4\1\121\10\4\2\0\1\4\1\43"+
    "\1\4\21\0\17\4\1\122\6\4\2\0\1\4\1\43"+
    "\1\4\21\0\22\4\1\123\3\4\2\0\1\4\1\43"+
    "\1\4\21\0\17\4\1\124\6\4\2\0\1\4\1\43"+
    "\1\4\21\0\13\4\1\125\12\4\2\0\1\4\1\43"+
    "\1\4\21\0\23\4\1\126\2\4\2\0\1\4\1\43"+
    "\1\4\21\0\17\4\1\127\6\4\2\0\1\4\1\43"+
    "\1\4\21\0\1\4\1\130\24\4\2\0\1\4\1\43"+
    "\1\4\21\0\2\4\1\131\23\4\2\0\1\4\1\43"+
    "\1\4\21\0\1\4\1\132\24\4\2\0\1\4\1\43"+
    "\1\4\21\0\11\4\1\133\14\4\2\0\1\4\1\43"+
    "\1\4\21\0\11\4\1\134\14\4\2\0\1\4\1\43"+
    "\1\4\21\0\23\4\1\135\2\4\2\0\1\4\1\43"+
    "\1\4\21\0\13\4\1\136\12\4\2\0\1\4\1\43"+
    "\1\4\21\0\7\4\1\137\16\4\2\0\1\4\1\43"+
    "\1\4\21\0\11\4\1\140\14\4\2\0\1\4\1\43"+
    "\1\4\21\0\10\4\1\141\15\4\2\0\1\4\1\43"+
    "\1\4\21\0\11\4\1\142\14\4\2\0\1\4\1\43"+
    "\1\4\21\0\12\4\1\143\13\4\2\0\1\4\1\43"+
    "\1\4\21\0\2\4\1\144\23\4\2\0\1\4\1\43"+
    "\1\4\21\0\13\4\1\145\12\4\2\0\1\4\1\43"+
    "\1\4\21\0\14\4\1\146\11\4\2\0\1\4\1\43"+
    "\1\4\21\0\5\4\1\147\20\4\2\0\1\4\1\43"+
    "\1\4\21\0\15\4\1\150\10\4\2\0\1\4\1\43"+
    "\1\4\21\0\11\4\1\151\14\4\2\0\1\4\1\43"+
    "\1\4\21\0\16\4\1\152\7\4\2\0\1\4\1\43"+
    "\1\4\21\0\17\4\1\153\6\4\2\0\1\4\1\43"+
    "\1\4\21\0\20\4\1\154\5\4\2\0\1\4\1\43"+
    "\1\4\21\0\15\4\1\155\10\4\2\0\1\4\1\43"+
    "\1\4\21\0\15\4\1\156\10\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3344];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\7\1\1\11\1\1\1\11\1\1\6\11"+
    "\16\1\2\0\6\11\104\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private void echo () { System . out . print (yytext ()); }

  public int position () { return yycolumn; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MicroPythonLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2618) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   { return new Token (Symbol . EOF); }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { echo();  ErrorMessage . print (yycolumn, "Illegal character");
            } 
            // fall through
          case 42: break;
          case 2: 
            { echo();
            } 
            // fall through
          case 43: break;
          case 3: 
            { echo();  return new Token (Symbol . ID, yytext ());
            } 
            // fall through
          case 44: break;
          case 4: 
            { echo();  return new Token (Symbol . INTEGER, yytext ());
            } 
            // fall through
          case 45: break;
          case 5: 
            { echo(); return new Token (Symbol . LT, yytext ());
            } 
            // fall through
          case 46: break;
          case 6: 
            { echo(); return new Token (Symbol . GT, yytext ());
            } 
            // fall through
          case 47: break;
          case 7: 
            { echo();  return new Token (Symbol . ASSIGN);
            } 
            // fall through
          case 48: break;
          case 8: 
            { echo();  return new Token (Symbol . PLUS);
            } 
            // fall through
          case 49: break;
          case 9: 
            { echo();  return new Token (Symbol . MINUS);
            } 
            // fall through
          case 50: break;
          case 10: 
            { echo();  return new Token (Symbol . TIMES);
            } 
            // fall through
          case 51: break;
          case 11: 
            { echo();  return new Token (Symbol . LPAREN);
            } 
            // fall through
          case 52: break;
          case 12: 
            { echo();  return new Token (Symbol . RPAREN);
            } 
            // fall through
          case 53: break;
          case 13: 
            { echo();  return new Token (Symbol . SEMICOLON);
            } 
            // fall through
          case 54: break;
          case 14: 
            { echo();  return new Token (Symbol . COLON);
            } 
            // fall through
          case 55: break;
          case 15: 
            { echo();  return new Token (Symbol . COMMA);
            } 
            // fall through
          case 56: break;
          case 16: 
            { echo();  return new Token (Symbol . PERIOD);
            } 
            // fall through
          case 57: break;
          case 17: 
            { echo(); return new Token (Symbol . LE, yytext ());
            } 
            // fall through
          case 58: break;
          case 18: 
            { echo(); return new Token (Symbol . GE, yytext ());
            } 
            // fall through
          case 59: break;
          case 19: 
            { echo(); return new Token (Symbol . EQ, yytext ());
            } 
            // fall through
          case 60: break;
          case 20: 
            { echo();  return new Token (Symbol . NE, yytext ());
            } 
            // fall through
          case 61: break;
          case 21: 
            { echo();  return new Token (Symbol . ARROW);
            } 
            // fall through
          case 62: break;
          case 22: 
            { echo();  return new Token (Symbol . SLASH);
            } 
            // fall through
          case 63: break;
          case 23: 
            { echo();  return new Token (Symbol . OR);
            } 
            // fall through
          case 64: break;
          case 24: 
            { echo();  return new Token (Symbol . IF);
            } 
            // fall through
          case 65: break;
          case 25: 
            { echo();  return new Token (Symbol . INT);
            } 
            // fall through
          case 66: break;
          case 26: 
            { echo(); return new Token (Symbol . NOT);
            } 
            // fall through
          case 67: break;
          case 27: 
            { echo();  return new Token (Symbol . AND);
            } 
            // fall through
          case 68: break;
          case 28: 
            { echo();  return new Token (Symbol . DEF);
            } 
            // fall through
          case 69: break;
          case 29: 
            { echo();  return new Token (Symbol . FROM);
            } 
            // fall through
          case 70: break;
          case 30: 
            { echo();  return new Token (Symbol . CONSTANT);
            } 
            // fall through
          case 71: break;
          case 31: 
            { echo();  return new Token (Symbol . TAIL);
            } 
            // fall through
          case 72: break;
          case 32: 
            { echo();  return new Token (Symbol . HEAD);
            } 
            // fall through
          case 73: break;
          case 33: 
            { echo();  return new Token (Symbol . NULL);
            } 
            // fall through
          case 74: break;
          case 34: 
            { echo();  return new Token (Symbol . ELSE);
            } 
            // fall through
          case 75: break;
          case 35: 
            { echo();  return new Token (Symbol . INPUT);
            } 
            // fall through
          case 76: break;
          case 36: 
            { echo();  return new Token (Symbol . PRINT);
            } 
            // fall through
          case 77: break;
          case 37: 
            { echo();  return new Token (Symbol . WHILE);
            } 
            // fall through
          case 78: break;
          case 38: 
            { echo();  return new Token (Symbol . RETURN);
            } 
            // fall through
          case 79: break;
          case 39: 
            { echo();  return new Token (Symbol . IMPORT);
            } 
            // fall through
          case 80: break;
          case 40: 
            { echo();  return new Token (Symbol . LIST);
            } 
            // fall through
          case 81: break;
          case 41: 
            { echo();  return new Token (Symbol . CLASS);
            } 
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
